return {
    ["anguish"] = {
        { name = "Administrator Charial", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Arch Magus Vangl",      statusImmunities = { Stun = true, Snare = true, }, },
        "Coerced Lieutenant",
        { name = "Damlin Lingering Charge", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "First Lieutenant Minas",  statusImmunities = { Stun = true, Snare = true, }, },
        "Frenzied Pit Fiend",
        { name = "Grenlok the Converter", statusImmunities = { Stun = true, Snare = true, }, },
        "Janzio",
        "Jelvan",
        { name = "Keldovan the Harrier",  statusImmunities = { Stun = true, Snare = true, }, },
        "Novara",
        "Ofanso",
        "Oshimai Spirit of the High Air",
        { name = "Overlord Mata Muram",  statusImmunities = { Stun = true, Snare = true, }, },
        "Raging Pit Hound",
        "Shalvo",
        { name = "Tanthi the Tormentor", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Tantho the Tormentor", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Tanthu the Tormentor", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Ture",                 statusImmunities = { Stun = true, Snare = true, }, },
        "Uchti",
        { name = "Vilria the Keeper", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Warden Hanvar",     statusImmunities = { Stun = true, Snare = true, }, },
        "Yuisaha",
    },
    ["befallen"] = {
        "Boondin Babbinsbort",
        "Devouring Shadowknight",
        "Dreaded Shadowknight",
        "Enchanted Elf Skeleton",
        "Gynok Moltor",
        "Hateful Shadowknight",
        "Malignant Shadowknight",
        "Priest Amiaz",
        "skeleton Lrodd",
        "Soulless Shadowknight",
        "The Thaumaturgist",
        "Zeek`s Shadow",
    },
    ["blackburrow"] = {
        "A Giant Plague Rat",
        "A Gnoll Brewer",
        "A Gnoll Commander",
        "A Gnoll Courier",
        "A Gnoll Tactician",
        "Lord Elgnub",
        "Mannan of the Sabertooth",
        "Master Brewer",
        "Refugee Splitpaw",
        "Socho Darkpaw",
        "Splitpaw Commander",
        "The Gnoll High Shaman",
        "Tranixx Darkpaw",
    },
    ["bloodfields"] = {
        "Caller Donivin",
        "Captain Gherish",
        "Clergyman Rexith",
        { name = "Elite Dragorn Jekisia", statusImmunities = { Stun = true, Snare = true, }, },
        "Gazz the Gargantuan",
        { name = "Girplan Slasher",       statusImmunities = { Stun = true, Snare = true, }, },
        "Golem Supplier",
        { name = "Guardian of Kaavi", statusImmunities = { Snare = true, }, },
        "High Priest Wersin",
        { name = "Ikaav Dominator",   statusImmunities = { Snare = true, }, },
        { name = "Ikaav Dreamweaver", statusImmunities = { Stun = true, Snare = true, }, },
        "Ikaav Slavetrader",
        "Ikaav Slumberer",
        "Ikaav Sorceress",
        "Ikaav Stormbringer",
        { name = "Kragsmash",  statusImmunities = { Snare = true, }, },
        "Lieutenant Lihad",
        "Noc Deathstalker",
        "Noc Slave Overseer",
        "The Domineering Ukun",
        "The Heavy Burdened Golem",
        { name = "The Keeper", statusImmunities = { Stun = true, Snare = true, }, },
        "Tormented Scout",
        "Ukun Hatemonger",
        { name = "War Caller Kaavi", statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["broodlands"] = {
        "Aqualung",
        "Firefang",
        "Flamefist",
        "Frostblind",
        "Frostfoot",
        "Greentooth",
        { name = "Grel Strongboom", statusImmunities = { Stun = true, Snare = true, }, },
        "Sandpaw",
        "Sandrender Xigazn",
        "Snowbrow",
        "Snowclaw",
        "Stone-Gazing Basilisk",
        "The Jungle Walker",
        "Viridix",
    },
    ["causeway"] = {
        "Alkron Wyrmsong",
        { name = "Alpha Feran",              statusImmunities = { Snare = true, }, },
        "Bazu Scavenger",
        { name = "Bazu Smasher",             statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Bone Cracker",             statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Drarakon the Mad",         statusImmunities = { Snare = true, }, },
        { name = "Elemental Essence Breeze", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Elemental Essence Gust",   statusImmunities = { Stun = true, Snare = true, }, },
        "Elemental Essence of Air",
        "Grinbar the Ancient",
        { name = "Guardian Etrias", statusImmunities = { Snare = true, }, },
        { name = "Guardian Naven",  statusImmunities = { Snare = true, }, },
        "Jillaa Oogblat",
        "Kupiop Iku",
        { name = "Lannal the Beast Tamer", statusImmunities = { Stun = true, Snare = true, }, },
        "Pixt Arreand Bodybender",
        "Pixt Trent",
        "Ridgerunner Droongar",
        "Ridgerunner Drunt",
        { name = "Slavedriver Menlo",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Stone Thrower",          statusImmunities = { Snare = true, }, },
        "Tarlang",
        { name = "Withering Murkglider", statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["cazicthule"] = {
        "a Tae Ew warlord",
        "a Tae Ew warmaster",
        "Dismay",
        "Dreadfang",
        "Frightchaser",
        "Soul Siphon",
        "Terrorclaw",
        "Toxiferious",
    },
    ["chambersa"] = {
        { name = "Master of Hate",  statusImmunities = { Stun = true, Snare = true, }, },
        "Shell of the Master",
        { name = "Voracious Feran", statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["chambersb"] = {
        { name = "Ansdaicher the Ancient",  statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Granite Stoneguardian",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Hemkai the Ascendant",    statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Hulking Bazu",            statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Steelshock",              statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Zellucheraz the Ancient", statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["chambersc"] = {
        "Dragorn Acolyte",
        "Dragorn Adept",
        "Dragorn Annihilator",
        "Dragorn Flamecaster",
        "Dragorn Incinerator",
        "Dragorn Spellscribe",
        { name = "Master of Subversion", statusImmunities = { Stun = true, Snare = true, }, },
        "Shell of the Master",
    },
    ["chambersd"] = {
        { name = "Enforcer of Efficiency",   statusImmunities = { Snare = true, }, },
        { name = "Master of Specialization", statusImmunities = { Stun = true, Snare = true, }, },
        "Master of Versatility",
        { name = "Muramite Commander", statusImmunities = { Snare = true, }, },
    },
    ["chamberse"] = {
        "Construct of Brutality",
        "Construct of Fire",
        "Construct of Ice",
        "Construct of Pain",
        "Construct of Power",
        { name = "Master of Adaptation", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Master of Ingenuity",  statusImmunities = { Stun = true, Snare = true, }, elementalImmunities = { Fire = true, Cold = true, Magic = true, Poison = true, }, },
    },
    ["chambersf"] = {
        { name = "Allaina Deepeyes",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Allionae Ullui",        statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Bavabwa Steeltoe",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Bibladrap Mindsnapper", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Cadavrox Bonebringer",  statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Carreenu Opulaae",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Deathwalker",           statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Eira Varinger",         statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Elennis Soulsaviour",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Endaar Flashpoint",     statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Enty Darkmask",         statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Esprit Boilingblood",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Etherrakor the Silent", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Faleniel the Pure",     statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Fiddap Clakburner",     statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Fimble Icecaster",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Fogge Armstorm",        statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Gaelin",                statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Ghurah",                statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Gizu Blackheart",       statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Griball Sizliv",        statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Hemik Pyus",            statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Ipputs Dagglebrap",     statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Javoldar",              statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Jolarrm Thoughtreaver", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Joner Tumble",          statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Kathien",               statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Kubaria",               statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Master of Destruction", statusImmunities = { Snare = true, }, },
        { name = "Mazzie Melkhor",        statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Melodite Arinal",       statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Mirendach",             statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Modus Apparition",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Nakert Grimmagus",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Nialle Luty",           statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Nicolai Yule",          statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Nimatrix Cloud",        statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Peavu Ix`Tim",          statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pellucid",              statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pirallan",              statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Reattim Heftsteel",     statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Rebthik Soulreaver",    statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Sammu Ionua",           statusImmunities = { Stun = true, Snare = true, }, },
        "Shell of the Corrupted",
        { name = "Sheru Embraciu",     statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Slly Stonestance",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Steelshadow",        statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Stoneheel Osprey",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Tempko",             statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Texur Shadowprey",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Tremura Soulheart",  statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Truwana Graveblood", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Uronius Hight",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Valerian Kimble",    statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Vavrix Rentu`Ivi",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Volen Flyingkick",   statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["charasis"] = {
        "Archivist of the Dead Tongue",
        "Custodian of Forbidden Rites",
        "Warden of Broken Oaths",
    },
    ["crushbone"] = {
        "Ambassador DVinn",
        "Emperor Crush",
        "Lord Darish",
        "Orc Scoutsman",
        "Orc Taskmaster",
        "Orc Thaumaturgist",
        "Orc Warden",
        "The Fabled Ambassador Dvinn",
        "The Fabled Emperor Crush",
        "The Prophet",
    },
    ["delvea"] = {
        "Boilingwind",
        "Burningfang",
        "Cloud of Smoke",
        "Crimsonwing",
        "Dark Webspinner",
        "Ezekl the Charred",
        "Forbin Mixmasher",
        { name = "Hulking Lavaspinner",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Lavaspinner Protector", statusImmunities = { Stun = true, Snare = true, }, },
        "Magma Spider",
        "Poisonfang",
        "Rysok the Vile",
        "Smoketail",
        { name = "Spider Broodmother", statusImmunities = { Stun = true, Snare = true, }, },
        "Stoneclaw",
        "Stonecluster",
        "Stonekrag",
        { name = "Stonemaw",           statusImmunities = { Stun = true, Snare = true, }, },
        "Tarpo Fiddengrab",
        { name = "Volkara", statusImmunities = { Stun = true, Snare = true, }, },
        "Wynne the Dark",
        "Zycem the Scorched",
    },
    ["delveb"] = {
        { name = "Emoush the Destroyer", statusImmunities = { Stun = true, Snare = true, }, },
        "Fire Goblin Laborer",
        "Fire Goblin Scribe",
        "Fire Goblin Strategist",
        "Fire Goblin Tracker",
        { name = "Gimblax",              statusImmunities = { Stun = true, Snare = true, }, },
        "Goblin King",
        "Goblin Servant",
        "Goblin Task Master",
        "Higglin Diggerchop",
        "Inquisitor Ukkag",
        { name = "Mystic Braggle", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Mystic Griknok", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Mystic Shiflor", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Tirranun",       statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["dranik"] = {
        "a cracked earthshaker",
        { name = "a Dragorn Prodigy",     statusImmunities = { Snare = true, }, },
        "Arlagai the Defiler",
        { name = "Battlemaster Rhorious", statusImmunities = { Snare = true, }, },
        { name = "Bloated Girplan",       statusImmunities = { Stun = true, Snare = true, }, },
        "Bolno the Peon",
        "Bowlord Rorn",
        "Daignal the Revered",
        "Dragorn Laborer",
        "Erana Farrel",
        "Filligno the Slayer",
        "Granitesmash",
        "Gronogg the Awful",
        "Guttertusk the Cruel",
        "Ikaav Slaveherder",
        "Illis Mindweaver",
        { name = "Krekk Brimblade",        statusImmunities = { Stun = true, Snare = true, }, },
        "Kyv Bowguard",
        "Kyv Bowhound",
        "Kyv Sharpshooter",
        "Kyv Sharpshooter Nass",
        "Lhranc",
        { name = "Lirah the Bridgekeeper", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Mistress Ujani",         statusImmunities = { Snare = true, }, },
        { name = "Murkglider Breeder",     statusImmunities = { Stun = true, Snare = true, }, },
        "Murkglider Deathsting",
        { name = "Noc Slavehunter", statusImmunities = { Snare = true, }, },
        { name = "Ornaia the Foul", statusImmunities = { Snare = true, }, },
        "Rargari the Destroyer",
        { name = "Reinad Scalebreath",     statusImmunities = { Snare = true, }, },
        "Siliena the Wicked",
        { name = "Souldrainer",            statusImmunities = { Snare = true, }, },
        { name = "Stoneworker Stonetooth", statusImmunities = { Snare = true, }, },
        { name = "Tiorpat Tornwing",       statusImmunities = { Stun = true, Snare = true, }, },
        "Tyian Rianda",
        { name = "Ukun Fleshhunter", statusImmunities = { Snare = true, }, },
        { name = "Ungi the Swift",   statusImmunities = { Snare = true, }, },
        "Ungorn the Furious",
        { name = "Vornad Deathtusk",   statusImmunities = { Snare = true, }, },
        { name = "Zun`Muram Volklana", statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["dranikcatacombsa"] = {
        "Dragorn Marshal Greshka",
        "High Enchantress Zy`chia",
        "Shade of Redis Linrok",
    },
    ["dranikcatacombsb"] = {
        "Elite Overlord Vijaz",
        "High Sorceress Vi`tara",
    },
    ["dranikcatacombsc"] = {
        "Elite Pixxt K`illiga",
        "Insidious Dragorn",
        "Master of the Watch",
    },
    ["dranikhollowsa"] = {
        "Discordling Hollower",
        "Girplan Pathmaker",
    },
    ["dranikhollowsb"] = {
        "Kyv Bowkeeper",
        "Ukun Fleshrender",
    },
    ["dranikhollowsc"] = {
        "a Shrewd Dragorn",
        "Inky Murkglider",
        { name = "Muridae the Plagued", statusImmunities = { Stun = true, Snare = true, }, },
        "Silentpaw",
    },
    ["draniksewersa"] = {
        "Craftsman Ferinio",
        "Stonefoot",
    },
    ["draniksewersb"] = {
        "Nightfang Glider",
        "Silania Janaid",
    },
    ["draniksewersc"] = {
        "Dragorn Foreman",
        "Ukun Sentinel",
    },
    ["draniksscar"] = {
        { name = "Blackfall Borer",       statusImmunities = { Snare = true, }, },
        { name = "Ertalon the Thrall",    statusImmunities = { Snare = true, }, },
        { name = "Fang",                  statusImmunities = { Snare = true, }, },
        { name = "Girztal the Attendant", statusImmunities = { Snare = true, }, },
        "Grathnok Gilforgan",
        "Karsor the Mad",
        { name = "Kiltarn the Sharp",           statusImmunities = { Snare = true, }, },
        { name = "Kirspos the Cruel",           statusImmunities = { Snare = true, }, },
        { name = "Kyv Bowmaster",               statusImmunities = { Snare = true, }, },
        { name = "Kyv Darkscout",               statusImmunities = { Snare = true, }, },
        { name = "Kyv HeadHunter",              statusImmunities = { Snare = true, }, },
        { name = "Murkglider Hiveguard",        statusImmunities = { Snare = true, }, },
        { name = "Murkglider Man O War",        statusImmunities = { Snare = true, }, },
        { name = "Murkglider Marroweater",      statusImmunities = { Snare = true, }, },
        { name = "Newborn Murkglider Devourer", statusImmunities = { Snare = true, }, },
        { name = "Noc Bloodtusk",               statusImmunities = { Snare = true, }, },
        { name = "Noc Razortusk",               statusImmunities = { Snare = true, }, },
        { name = "Scaleback",                   statusImmunities = { Snare = true, }, },
        { name = "Ukun BoneRetriever",          statusImmunities = { Snare = true, }, },
        { name = "Ukun Gutfeaster",             statusImmunities = { Snare = true, }, },
        { name = "Ukun Slavehunter",            statusImmunities = { Snare = true, }, },
        "Yerika Sisslak",
    },
    ["eastkorlacha"] = {
        "Fenrir The Bloodfang Alpha",
        "Hati the Bonecrusher",
        "Skoll the Shadowfang",
    },
    ["everfrost"] = {
        "Goblin Diver",
        "Karg IceBear",
        "Redwind",
        "Tainted Wooly Mammoth",
        "Vengeful Composer",
        "Vengeful Lyricist",
        "Vengeful Soloist",
    },
    ["frozenshadow"] = {
        "Elusive Henchman",
    },
    ["gukbottom"] = {
        "A Frenzied Ghoul",
        "A Froglok Crusader",
        "A Froglok Herbalist",
        "A Froglok Noble",
        "A Froglok Tactician",
        "A Ghoul Assassin",
        "A Ghoul Cavalier",
        "A Ghoul Executioner",
        "A Ghoul Ritualist",
        "A Ghoul Sage",
        "A Ghoul Savant",
        "A Ghoul Sentinel",
        "A Ghoul Supplier",
        "A Minotaur Elder",
        "A Minotaur Patriarch",
        "A Reanimated Hand",
        "the froglok king",
        "The Ghoul Arch Magus",
        "The Ghoul Lord",
    },
    ["guktop"] = {
        "A Froglok Gaz Squire",
        "A Froglok Idealist",
        "A Froglok Realist",
        "A Froglok Scryer",
        "A Froglok Summoner",
        "A Giant Heart Spider",
        "The Froglok Shin Lord",
        "The Froglok Warden",
    },
    ["harbingers"] = {
        { name = "Asus the Quick", statusImmunities = { Stun = true, Snare = true, }, },
        "Builder Gorb",
        "Foreman Guppu",
        "Girplan Architect",
        "Guardsman Quilm",
        "Inventor Krang",
        "Karg the Fiend",
        "Loyal Servant Ziym",
        "Overseer Rowgar",
        "Peon Salnar",
        "Retind Oaln",
        "Revolter Yernom",
        "Taskmaster Yarln",
        "The Prime Mover",
        "Toiler Opanin",
        "Trainer Cyrum",
        "Trainer Dysarth",
        "Varin Deathclaw",
        { name = "Windrush",       statusImmunities = { Snare = true, }, },
    },
    ["hole"] = {
        "Dartain the Lost",
        "Fabled Master Yael",
        "Fabled Nortlav the Scalekeeper",
        "Initiate Sirlis",
        "Master Yael",
        "Nortlav the Scalekeeper",
        "Rocksoul",
        "Schnozz the Flighty",
        "Slizik the Mighty",
        "Stonesoul the Unmoving",
        "Ulrik the Devout",
    },
    ["ikkinz"] = {
        { name = "Altar Construct",         statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Altar Overseer",          statusImmunities = { Slow = true, Stun = true, }, },
        { name = "Altar Sentry",            statusImmunities = { Slow = true, }, },
        { name = "Altar Sustainer",         statusImmunities = { Stun = true, }, },
        { name = "Altar Warden",            statusImmunities = { Slow = true, Stun = true, }, },
        { name = "Controlled Spirithunter", statusImmunities = { Stun = true, Snare = true, }, },
        "Cruel Illusion",
        "Crumbling Monolith",
        "Curate Firetender",
        { name = "Custodian of Righteousness", statusImmunities = { Slow = true, Stun = true, }, },
        { name = "Defender of Righteousness",  statusImmunities = { Slow = true, Stun = true, }, },
        { name = "Diabolic Destroyer",         statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Flesh Hunter",               statusImmunities = { Slow = true, Stun = true, }, },
        "Guardian of Glorification",
        { name = "Guardian of Righteousness",  statusImmunities = { Slow = true, Stun = true, }, },
        { name = "Guardian of Transcendence",  statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Hexxt Markmaker",            statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Hexxt Sightsliverer",        statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Malevolent Priest",          statusImmunities = { Slow = true, Stun = true, }, },
        { name = "Oracle of the Altar",        statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Phantasmal Priest",          statusImmunities = { Slow = true, Stun = true, }, },
        { name = "Phantasmal Priest Guardian", statusImmunities = { Slow = true, }, },
        { name = "Pixtt Annihilator",          statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pixtt Assault Ward",         statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pixtt Condemner",            statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pixtt Decimator",            statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pixtt Slaughterer",          statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pixtt Tyrannist",            statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pixtt Willbreaker",          statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Priest of Righteousness",    statusImmunities = { Slow = true, Stun = true, }, },
        { name = "Rav Interceptor",            statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Sentinel of Glorification",  statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        "Spirit of Tunik Tamuik",
        { name = "Stalwart Caretaker",     statusImmunities = { Slow = true, Snare = true, }, },
        { name = "Subjugated Vrex Caller", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Transcendent Acolyte",   statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Visionary of Glory",     statusImmunities = { Slow = true, Stun = true, }, },
        "Vrex Xalkak Nixki",
        "Vrex Xalkak`s Marauder",
    },
    ["inktuta"] = {
        "Cursecaller Fhqwhgads",
        "Cursecaller Kiamquz",
        "Cursecaller Qibaiz",
        "Cursecaller Requarak",
        "Cursecaller Towzaqu",
        "Cursecaller Xavonique",
        "Jomica the Unforgiven",
        "Kelekdrix, Herald of Trushar",
        { name = "Nijacka the Scourge",  statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        "Noqufiel",
        "True Image of Noqufiel",
        { name = "Usher of Kelekdrix",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Watcher of Kelekdrix", statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["karnor"] = {
        "The Legendary Venril Sathir",
    },
    ["kithicor"] = {
        "The Doll Maker",
    },
    ["mistmoore"] = {
        "a cloaked dhampyre",
        "Carmilla",
        "Countess Elizabeth Bathory",
        "Garton Viswin",
        "Lasna Cheroon",
        "Mynthi Davissi",
        "Princess Cherista",
        "William the Bloody",
    },
    ["najena"] = {
        "Akksstaff",
        "BoneCracker",
        "Drelzna",
        "Ekeros",
        "Moosh",
        "Najena",
        "Officer Grush",
        "Rathyl",
        "Tentacle Terror",
        "The Guard Captain",
        "The Widowmistress",
        "Trazdon",
    },
    ["oasis"] = {
        "Arthikus",
        "Cazel",
        "Elder Ronin",
        "Hatar",
        "Lockjaw",
        "The Dervish Thug",
    },
    ["oot"] = {
        "A Goblin Headmaster",
        "a land shark",
        "Allizewsaur",
        "An Ancient Cyclops",
        "Boog Mudtoe",
        "Dixl Drool",
        "Goob Mudtoe",
        "Gornit",
        "Gull Skytalon",
        "Isle Goblin Chieftan",
        "Soarin Brightfeather",
        "tainted seafury cyclops",
        "Toko Binlittle",
    },
    ["paw"] = {
        "Brother Gruff",
        "Kurrpok Splitpaw",
        "Nisch Val Torash Mashk",
        "Rosch Val L`Vlor",
        "Tesch Val Deval`Nmak",
        "Tesch Val Kadvem",
        "The Ishva Mal",
        "Verishe Mal Executioner",
        "Verishe Mal Judge",
    },
    ["permafrost"] = {
        "A Goblin Archeologist",
        "A Goblin Jailmaster",
        "A Goblin Patriarch",
        "A Goblin Preacher",
        "A Goblin Scryer",
        "An Ice Goblin Alchemist",
        "High Priest Zaharn",
        "King Thex`Ka IV",
        "Lady Vox",
    },
    ["potimeb"] = {
        "Bertoxxulous",
        "Cazic Thule",
        "Innoruuk",
        "Quarm",
        "Rallos Zek",
        "Saryrn",
        "Tallon Zek",
        "Terris Thule",
        "Vallon Zek",
    },
    ["provinggrounds"] = {
        "a Dragorn Tactician",
        "Aneuk Tyrannist",
        "Battlemaster Denik",
        "Blind Hunter Rekamu",
        "Cadavor Fonidan",
        "Captor Supplescale",
        "Cleaver Wiex",
        "Diad the Devourer",
        "Diodite Bluespark",
        "Discordling Enchainer Kuroun",
        "Fleshthreader Dashii",
        { name = "Girplan Scavenger",      statusImmunities = { Snare = true, }, },
        "Hunter Leisov",
        "Kyv Hunter Lheun",
        "Lieutenant Commander Nak`Muram",
        { name = "Lightningcaller Vhalek", statusImmunities = { Slow = true, Snare = true, }, },
        "Miseryfiend Ghio",
        "Neuromancer Vionne",
        "Noc Bloodluster Zieh",
        "Odiumate Isienne",
        "Pashia Clouddancer",
        { name = "Possessed Brute", statusImmunities = { Snare = true, }, },
        "Sentinel Siofet",
        "Stilled Lightning Warrior",
        "Stormer",
        "Strategist Kin`Muram",
        "Taskfiend Caikap",
    },
    ["qeytoqrg"] = {
        "Gnasher Furgutt",
        "Hadden",
        "Holly Windstalker",
        "Pyzjn",
        "Scruffy",
        "Tovax Vmar",
        "Varsoon",
        "Yollis Jenkins",
    },
    ["qvic"] = {
        { name = "Cynosure Kvanjji",  statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Dvoin M`sha",       statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Hexxt Ilk Klokk",   statusImmunities = { Stun = true, }, },
        { name = "Hexxt Jkak Miq",    statusImmunities = { Stun = true, }, },
        { name = "Hexxt Pvin Nki",    statusImmunities = { Stun = true, }, },
        { name = "Iqthinxa Karnkvi",  statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Mnat M`sha",        statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pixtt Invi Mal",    statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pixtt Llan Kvish",  statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pixtt Sho`Val Kqi", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Pixtt Ttinq Val",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Ptav M`sha",        statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Tiv Ashmmi",        statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Vrex Indra",        statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["riftseekers"] = {
        "a Dragorn Battlemaster",
        "Balancer Relik",
        { name = "Chailak",             statusImmunities = { Snare = true, }, },
        "Channeler Pyren",
        "Companion Prefect",
        { name = "Craftmaster Tieranu", statusImmunities = { Stun = true, Snare = true, }, },
        "Cyrec the Arcane",
        "Discordling Gemkeeper",
        "Discordling Shardmender",
        "Elite Aneuk Miseryfiend",
        "Familiar Venomtail",
        { name = "Feratha",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Flamegore", statusImmunities = { Stun = true, Snare = true, }, },
        "Frostkeeper Rybah",
        "Gelidran Conjurer",
        "Gelidran Frostformer",
        "Gelidran Icekeeper",
        "Girplan Shardtender",
        "Girplan Stonesinger",
        { name = "Hotspot",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "King Gelaqua", statusImmunities = { Snare = true, }, },
        "Mistwalker",
        "Pyrilen Researcher",
        "Pyrilen Riftseeker",
        "Pyrilen Summoner",
        { name = "Queen Pyrilonis", statusImmunities = { Snare = true, },              elementalImmunities = { Fire = true, }, },
        "Ruiner Isaka",
        "Shadowstalker",
        { name = "Sizzle",          statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["runnyeye"] = {
        "A Pickclaw Crusader",
        "A Slime Elemental",
        "Battlelord Paluk",
        "Battlewizard Unak",
        "Goblin Janitor",
        "Lord Pickclaw",
        "The Sporali Moldmaster",
    },
    ["sebilis"] = {
        "Arch Duke Iatol",
        "Baron Yosig",
        "Blood of Chottal",
        "Brogg",
        "Crypt Caretaker",
        "Emperor Chottal",
        "Frenzied Pox Scarab",
        "Froggy",
        "Froglok Armorer",
        "Froglok Armsman",
        "Froglok Bartender",
        "Froglok Chef",
        "Froglok Commander",
        "Froglok Ostiary",
        "Froglok Pickler",
        "Froglok Repairer",
        "Froglok Watcher",
        "Gangrenous Scarab",
        "Gruplinort",
        "Harbinger Freglor",
        "Hierophant Prime Grekal",
        "Myconid Assassin",
        "Myconid Spore King",
        "Sebilite Guardian",
        "Sebilite Protector",
        "The Legendary Trakanon",
        "Tolapumj",
    },
    ["soldunga"] = {
        "Captain Bipnubble",
        "CWG Model EXG",
        "Fire Goblin Bartender",
        "Flame Goblin Foreman",
        "Gabbie Mardoddle",
        "Goblin Drunkard",
        "Goblin High Shaman",
        "Inferno Goblin Captain",
        "Inferno Goblin Torturer",
        "Kindle",
        "Kobold Predator",
        "Lord Gimblox",
        "Lynada the exiled",
        "Reckless Efreeti",
        "Singe",
        "Solusek goblin king",
    },
    ["soldungb"] = {
        "Death Beetle",
        "Efreeti Lord Djarn",
        "Guano Harvester",
        "King Tranix",
        "Kobold Champion",
        "Kobold Noble",
        "Kobold Priest",
        "Lord Nagafen",
        "Magus Rokyl",
        "Noxious Spider",
        "Solusek kobold king",
        "Stone Spider",
        "Warlord Skarlon",
    },
    ["southkarana"] = {
        "Gnashmaw",
        "Gnawfang",
        "Grizzleknot",
        "Groi Gutblade",
        "Knari Morawk",
        "Kroldir Thunderhoof",
        "Marik Clubthorn",
        "Mroon",
        "Narra Tanith",
        "Nisch Val Torash Mashk",
        "Rosch Val L`Vlor",
        "Shaman Lenrel",
        "Shaman Ren`Rex",
        "Synger Foxfyre",
        "Tesch Val Deval`Nmak",
        "Tesch Val Kadvem",
    },
    ["stillmoona"] = {
        "a silent hunter",
        "Bathouse Manager Hakvar",
        "Decrepit Guard",
        "Guard Musashi",
        "Guard Nobunaga",
        "Hervash the Foreman",
        "Hong Lei",
        "Jadewing",
        "Jorvash the Usurper",
        "Osashi",
        { name = "Shogurei, Guardian of the Sands", statusImmunities = { Stun = true, Snare = true, }, },
        "Stillmoon courtyard gardener",
        "Stillmoon Forest Keeper",
        "Stillmoon henchman",
        "Stillmoon plan keeper",
        "Stoneskin",
        "Temple Foreman Korsav",
        "The Keeper of Strength",
        "The Keeper of Wisdom",
        "Tunk the Fluid",
        "Wei Chung",
        "Wei Zhang",
    },
    ["stillmoonb"] = {
        "crazed statue",
        { name = "Kessdona the Enlightened", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Rikkukin the Defender",    statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["tacvi"] = {
        "a corrupted construct",
        "Pixtt Kretv Kakxt",
        "Pixtt Kretv Krakxt",
        "Pixtt Riel Tavas",
        "Pixtt Xxeric Kex",
        { name = "Sesnil Yisnon", statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        "Tunat`Muram Cuu Vauax",
        "Zun`Muram Kvxe Pirik",
        "Zun`Muram Mordl Delt",
        "Zun`Muram Shaldn Boc",
        "Zun`Muram Yihst Vor",
    },
    ["thenest"] = {
        "Adel`ek",
        "Adenox",
        "Ainslin",
        "Bearsmasher",
        "Bentwing the Bloodthirsty",
        "Defender Tyothil",
        "Eggtender Nim",
        "Elureh",
        "Fahsheer Delure",
        "Ferrin Stoneheart",
        "Feryda",
        "Gimblemort",
        "Guardian Nameyn",
        "Hatchery Guard Pip",
        "Henry Firemind",
        "Ju`rek the Corrupted",
        "Kami",
        "Keentooth, Tribal Elder",
        "Kerosek",
        "Lavawalker",
        "Magmeran",
        "Merdith",
        "Protector Kanadin",
        "Rampaging Monolith",
        "Redeyes Lore Eater",
        "Sandwatcher Kolein",
        "Seism",
        "Sentinel Pafyr",
        "Shadedshard",
        "Shala Belen",
        "Silverclaw",
        { name = "T`Shara",              statusImmunities = { Stun = true, Snare = true, }, },
        "Temblor",
        { name = "Vishimtar the Fallen", statusImmunities = { Stun = true, Snare = true, }, },
    },
    ["thundercrest"] = {
        "Breath of Yar`Lir",
        "Claws of Yar`Lir",
        { name = "Clayforged Protector", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Disciple of Earth",    statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Disciple of Fire",     statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Disciple of Metal",    statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Disciple of Water",    statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Disciple of Wood",     statusImmunities = { Stun = true, Snare = true, }, },
        "Fersama",
        "Fumi the Vigilant",
        "Goblin Gardener",
        "Gox Ironmaw",
        { name = "Grandmaster Beetle", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Grandmaster Puma",   statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Grandmaster Snake",  statusImmunities = { Stun = true, Snare = true, }, },
        "Hidekazu",
        "Hidetada",
        { name = "Ironforged Protector",  statusImmunities = { Stun = true, Snare = true, }, },
        "Kafu the Turbulent",
        "Kodama the Voltaic",
        "Kunz Boomsetter",
        { name = "Lore Warden",           statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Master of Contentment", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Master of Deceit",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Master of Doubt",       statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Master of Rage",        statusImmunities = { Stun = true, Snare = true, }, },
        "Mihoko the Rector",
        { name = "Muligiwa the Toxic", statusImmunities = { Stun = true, Snare = true, }, },
        "Ninsei the Tempest",
        "Rinako the Stalwart",
        { name = "Shadowspitter",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Silk",               statusImmunities = { Stun = true, Snare = true, }, },
        "Sor Stormreach",
        { name = "Steel",              statusImmunities = { Stun = true, Snare = true, }, },
        "Storm Guardian",
        { name = "Storm Reach Sensei", statusImmunities = { Stun = true, Snare = true, }, },
        "Sugita the Vicarious",
        "Toshiharu",
        "Toshinobu",
        "Wings of Yar`Lir",
        "Yar`Lir",
        { name = "Yar`Lir the Living Storm", statusImmunities = { Stun = true, Snare = true, }, },
        "Yoshiaga",
        "Yoshihiro",
    },
    ["txevu"] = {
        { name = "Ancient Cragbeast Matriarch", statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Aneuk Nyrt Ymosa",            statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Aneuk Rilst Uskst",           statusImmunities = { Stun = true, Snare = true, }, },
        "High Priest Nkosi Bakari",
        { name = "Ikaav Nysf Lleiv",     statusImmunities = { Stun = true, Snare = true, },              elementalImmunities = { Poison = true, }, },
        "Inquisitor Chiak Tansk",
        "Inquisitor Lliev Kinth",
        "Ixt Hsek Syat",
        { name = "Ixt Kial Ivesi",       statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Ixt Quall Nalnn",      statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Mastruq Beast Warden", statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Mastruq Champion",     statusImmunities = { Stun = true, Snare = true, }, },
        "The Runt",
        { name = "Ukun Bloodfeaster",       statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Vrex Invoker Akello",     statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Vrex Invoker Jahzara",    statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Vrex Invoker Kashka",     statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Vrex Invoker Malik",      statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Vrex Invoker Raziya",     statusImmunities = { Stun = true, Snare = true, }, },
        { name = "Vrex Stonemaster Hateq",  statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Vrex Stonemaster Lorasa", statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Vrex Stonemaster Veset",  statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Zun`Muram Tkarish Zyk",   statusImmunities = { Stun = true, Snare = true, },              elementalImmunities = { Fire = true, Cold = true, Magic = true, Poison = true, Disease = true, }, },
    },
    ["unrest"] = {
        "A Reanimated Hand",
        "An Undead Barkeep",
        "An Undead Knight of Unrest",
        "Garanel Rucksif",
        "Reclusive Ghoul Magus",
        "Torklar Battlemaster",
    },
    ["uqua"] = {
        "Devastating Construct",
        "Guardian of Destruction",
        { name = "Spectral Trushar Worshipper", statusImmunities = { Snare = true, }, },
        { name = "Tqiv Araxt the Enraged",      statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Tqiv Qukret the Furious",     statusImmunities = { Slow = true, Stun = true, Snare = true, }, },
        { name = "Vrex Barxt Qurat",            statusImmunities = { Slow = true, }, },
    },
    ["wallofslaughter"] = {
        "a Dragorn Mastermind",
        "Bazu Bonesmasher",
        "Bazu Destroyer",
        "Chimera Deathbringer",
        "Chimera Seether",
        "Cipheron",
        "Dark Disciple",
        "Discordling Bloodfiend",
        "Discordling Chaosfiend",
        { name = "Discordling Warfiend", statusImmunities = { Snare = true, }, },
        "Dragorn Blightkeeper",
        { name = "Dragorn Champion",     statusImmunities = { Stun = true, Snare = true, }, },
        "Dragorn Nightwalker",
        "Dragorn Strategist",
        "Dragorn Turretkeeper",
        "Durunal the Cursebearer",
        "Feran Bloodkeeper",
        "Feran Savageclaw",
        { name = "Girplan Guardian", statusImmunities = { Stun = true, Snare = true, }, },
        "Girplan Mastercrafter",
        "Girplan Taskmaster",
        { name = "Herrian Warfrost", statusImmunities = { Stun = true, Snare = true, }, elementalImmunities = { Cold = true, }, },
        "Hudar Trittan",
        { name = "Hulcror",      statusImmunities = { Stun = true, Snare = true, }, },
        "Kyv Assassin",
        "Kyv Pureshot",
        "Lightning Lord",
        "Noc Bonecleaver",
        "Noc Shadowkeeper",
        "Pyrique Redwing",
        "Pyrique`s Shadow",
        "Shadowhunter",
        { name = "Tarn Icewind", statusImmunities = { Stun = true, Snare = true, }, },
        "The Murkglider Hivequeen",
        "Ukun Fleshflayer",
        "Ukun Tendonslicer",
        "Velitorkin",
    },
}
