return {
    Devs = {
        'Derple',
        "Algar",
    },
    Contributors = {
        'Morisato',
        'Greyn Artestre',
        'Postleaf',
        'Werkfakter',
        'SonicZentropy',
        'Tiddliestix',
        "Grimmier",
        "cannonballdex",
        "RobbanEQ",
        "mackal",
        "guest01",
        "Fargrim",
        "gennro",
        "Nunno",
        "No_Songs_For_You",
        "Zat",
        "aspire",
        "Hazado",
    },
}
